alipay:
  # appid
  appId: 9021000134659101
  # 客户私钥
  privateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC8vLKs5xLN92RevreDFVK+2FCl3lLB1We44NDg0cVTwFgE5z5iWGE15tYaMNuyOUn98aRxdZ8SGAwzsG30Amrbu8tUChq9dWENlp0p5qWsP0uBkcYfgeIDmcBnZACZGyy2I0mEewMfWOEC9omxt1+V0qkWfvAIgADKZ7y5CA+6Uvs5xYVfNr9c034bDwdeApiC8B4YmjjuECD0bIWBYBkHOSs36dGnVsuDVRGUtm1KDoykjnogvqdYQlofRaxm/EyV9HUrSlvY/+4XpnLcArfNigE0Za5mhpHGFuunL2U0pVbVzqETAM8sw0IGLkCBW/U2MIllHQIn/ozrYM0y7kwzAgMBAAECggEBALrippIq5SXpuAtREenMrXioPYNg19VzeRdKFcroLFq39PA2AkHjfa6f+pVIl+Ksc6XvJoPqki6afUqZgubBlgoqtDVtI/lCR23rG4ioCJi8vAl6zRHZzHEAR9KY5Ta1/9oCqwNxwy/BFF2YvdOp3g4+4IuT+h6QkTfa7LbTUq+NUgFSNImDcD1hB3yJKriP7ptZ1EENGaJ3+bmLLtOF2zissKQLg2mxvBGFx2U9eswTVh10XLcz8pR2mF57VpeTuema+FwqsxTwo02FMN0o/qP+X/OlADt6eQEIBKUGj8WqcRxIiB7syoFQ5rkW1J7uFrOYpmP7Rs1kftJjd7sC8PECgYEA81Yi0JE9yFkAWX7qrb7ULk3401NBCiQbGZfI941rp8jB1aWMoqhWtGqXgiDfYVnksQGkKcvQEjpXcOSq+3rIZfgI6jCHVYMBlC7ii632WI63G0HAgUQU+8U21ulXu5e+Z2X9BxPvXx5I9EiX0ojjte6iGynjjNcDUQzgY/UBk48CgYEAxo8opNY1pXBuPLD37PTw1Jh8bw95ubbJV5xeeFUHM4sz3Q1jjYLRhInxmw3qkNnt9z9eMMIv6SpIv7lxEXdmqm+qqlA0PQF0oEcT7XuAwU/EX5Ol/Uv/FmFQ6gevpHO7eavCRynh5WamA1D0cgjmvsGPCcSmbc99MZHJvQOHmx0CgYEAit5YZgDNan3oZiq5EUi7XGWhIDD+CCSM1rE5vpUVoB5BCIU+2kEJolLGfjv2X19m1OFj53pqF0z2Q/Yr4fKzVQYVSFlDkrh9+Sw8m4w+71EbDFIc42iQNRLadhGawPMbdXTNzvFAhV8KMWcQRdVbZqN2HdxtAR5fxSx9Dm5vZN8CgYAlOevV069lIAoa6Nbinx2Tzi7uJ4mbzvA6s79mchKSkFOd6weyHUeowLACcP58P8+EnmXLYGzZGytefqb7LlaaN6tYmQbiNSancgwDZzdBhvH7NVRWg+wERySDbAN7IpOQgSpAa1LFzpPrZT8fLhoMw39MxoipZ9BB/eJDxKik5QKBgQDfNciJr+HH2Gt7/I5bSndNivu6Wa1u4faCaT037XO8aBKt2hLgX8QQSlimpr6bFhbz7I+sE7/2Mnyne63DsElAJ/gOlSrnYH+aUd0sX/ia9rWwSPh4Md97vSz90EafwsKehf7kFKU6TwruAcCSsFiVIEmEqhmt3TvBsUwSDvnAuw==
  # 支付宝公钥
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg38/eODRn2ZKwR1vYFjiS5h5BE7BanYd71a09vjrjMACV2DPvj1cV9tGMVCrri+HthgB8jdy2GFqiBhLpnNuBPRhw9RLdnE+sTNKZx9gqMw3o0zELTfa0SmvSLsKD1PNhaxhnrA9nWRnHc1TnEPDM29ktcoOPN6mYVzO6tEzC2WyCq1jJ7PlwCIQ4ANEbrE0WNisxSIn9HLZJngImfkJ/hko4PhhFK+Df0SQbqbvEw11D+2iBIxgUUvRRNS9KNJ5fxEjRb70OWvdXZI1rk27gSxo6GY9zydgTVPZBxrecfvSy/ja8vjiJ/IrdgDEMlsng/szXbGwgZu4CtART+KSyQIDAQAB
  # 支付宝网关
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  # 回调地址
  notifyUrl: http://localhost:3090/
  # 支付完成后返回的地址
  returnUrl: http://localhost:3090/
  # 签名方式
  signType: RSA2
  # 字符编码格式
  charset: utf-8
  # 格式
  format: json

